version: '3.8'

services:
  ecommerce:
    image: postgres:15
    container_name: ecommerce
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0000
      POSTGRES_DB: ecommerce-db
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
